### ISSUE TITLE
Ionic beta 10 and Ionic CLI 

### ISSUE THREAD

**Issue by numerized** [mjwheatley/Ionic2-Meteor1.3-Starter#11]
Hi mate, good job, I've spent 2 days trying to make ionic2 and meteor work together, I think you are not too far to have a perfect starter here.

What about having the Ionic-CLI to use Ionic-View and other great services from Ionic.

What about updating to last version of Ionic beta 10 ?
Thanks !

**Comment by numerized** [comment]
I am definitely interested in this starter but I'm not able to launch it in an actual iOS 9.3 phone, neither on a simulator. All is compiling great and works locally wonderfully but gives a grey screen after splash screen.

**Comment by mjwheatley** [comment]
Not easy to keep up with all the different betas because of version dependencies and breaking changes.  If you do get it working, please send a Pull Request and help update this starter.

Unfortunately you will not be able to use the Ionic-CLI because this is a Meteor application.  However you could develop the client UI as an Ionic application and just migrate it into this Meteor app.  You would just have to update your imports.

How are you starting the project? `meteor run iso-device`?
When running the application that way I noticed an error message of "Cannot read property 'public' of undefined."  This is referring to Meteor.settings.public.appName in the app.ts file.
I have configured this project to be dependent on a settings.json file which contains the app's name.  You would need to use the following command to start the app from the command line `meteor run iso-device --settings ../config/development/settings.json`

That is the same command executed when running `npm start`.  You can also edit the package.json script for "meteor" to the same command so that you can use `npm start` to run the application on a device.  The application loads up on the emulator for iPhone 6s (9.3) when you include the settings.json.

**Comment by numerized** [comment]
Ok thanks for the reply. 

Let me try this I'll let you know

**Comment by numerized** [comment]
`meteor run ios-device --settings ../config/development/settings.json`

Worked ! Thanks a lot, I'll definitely try to update it and let you know.

I think you should report this command to run on device on your repo readme 🎱

**Comment by mjwheatley** [comment]
Good suggestion, I'll definitely do that.

**Comment by mjwheatley** [comment]
I just updated the project to use Ionic2 Beta 10 and updated the README.

**Comment by numerized** [comment]
Thanks, I'll have a look.
